## Importing Libraries

In [4]:
%matplotlib inline

from pathlib import Path

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

### Path to the competition data

In [5]:
DATA_DIR_COMPETITION = Path('/Users/joscha/Library/Mobile Documents/com~apple~CloudDocs/Studienarbeit/Daten')

### Path to the original data

In [6]:
DATA_DIR_ORIGINAL = Path('/Users/joscha/Library/Mobile Documents/com~apple~CloudDocs/Studienarbeit/Original Datensatz')

### Loading the data

In [7]:
competition_data = pd.read_csv(DATA_DIR_COMPETITION / 'train_values.csv', index_col='building_id')
original_data = pd.read_csv(DATA_DIR_ORIGINAL / 'csv_building_structure.csv', index_col='building_id')

### Overview of the data

In [8]:
# Competition Data
competition_data
#competition_data.head()

,geo_level_1_id,geo_level_2_id,geo_level_3_id,count_floors_pre_eq,age,area_percentage,height_percentage,land_surface_condition,foundation_type,roof_type,...,has_secondary_use_agriculture,has_secondary_use_hotel,has_secondary_use_rental,has_secondary_use_institution,has_secondary_use_school,has_secondary_use_industry,has_secondary_use_health_post,has_secondary_use_gov_office,has_secondary_use_use_police,has_secondary_use_other
building_id,,,,,,,,,,,,,,,,,,,,,
802906,6,487,12198,2,30,6,5,t,r,n,...,0,0,0,0,0,0,0,0,0,0
28830,8,900,2812,2,10,8,7,o,r,n,...,0,0,0,0,0,0,0,0,0,0
94947,21,363,8973,2,10,5,5,t,r,n,...,0,0,0,0,0,0,0,0,0,0
590882,22,418,10694,2,10,6,5,t,r,n,...,0,0,0,0,0,0,0,0,0,0
201944,11,131,1488,3,30,8,9,t,r,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
688636,25,1335,1621,1,55,6,3,n,r,n,...,0,0,0,0,0,0,0,0,0,0
669485,17,715,2060,2,0,6,5,t,r,n,...,0,0,0,0,0,0,0,0,0,0
602512,17,51,8163,3,55,6,7,t,r,q,...,0,0,0,0,0,0,0,0,0,0
151409,26,39,1851,2,10,14,6,t,r,x,...,0,0,0,0,0,0,0,0,0,0
747594,21,9,9101,3,10,7,6,n,r,n,...,0,0,0,0,0,0,0,0,0,0

In [9]:
# Original Data
original_data
#original_data.head()

,district_id,vdcmun_id,ward_id,count_floors_pre_eq,count_floors_post_eq,age_building,plinth_area_sq_ft,height_ft_pre_eq,height_ft_post_eq,land_surface_condition,...,has_superstructure_mud_mortar_brick,has_superstructure_cement_mortar_brick,has_superstructure_timber,has_superstructure_bamboo,has_superstructure_rc_non_engineered,has_superstructure_rc_engineered,has_superstructure_other,condition_post_eq,damage_grade,technical_solution_proposed
building_id,,,,,,,,,,,,,,,,,,,,,
120101000011,12,1207,120703,1,1,9,288,9,9,Flat,...,0,0,0,1,0,0,0,Damaged-Used in risk,Grade 3,Major repair
120101000021,12,1207,120703,1,1,15,364,9,9,Flat,...,0,0,0,1,0,0,0,Damaged-Repaired and used,Grade 5,Reconstruction
120101000031,12,1207,120703,1,1,20,384,9,9,Flat,...,0,0,0,0,0,0,0,Damaged-Repaired and used,Grade 2,Minor repair
120101000041,12,1207,120703,1,1,20,312,9,9,Flat,...,0,0,0,0,0,0,0,Damaged-Repaired and used,Grade 2,Minor repair
120101000051,12,1207,120703,1,1,30,308,9,9,Flat,...,0,0,0,0,0,0,0,Damaged-Repaired and used,Grade 1,Minor repair
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
366709001241,36,3603,360302,2,0,60,165,18,0,Flat,...,0,0,0,0,0,0,0,Damaged-Rubble clear,Grade 5,Reconstruction
366709001251,36,3603,360302,2,0,35,342,18,0,Flat,...,0,0,0,0,0,0,0,Damaged-Rubble clear,Grade 5,Reconstruction
366709001261,36,3603,360302,2,0,35,342,18,0,Flat,...,0,0,0,0,0,0,0,Damaged-Rubble clear,Grade 5,Reconstruction
366709001271,36,3603,360302,2,0,19,306,18,0,Flat,...,0,0,0,0,0,0,0,Damaged-Rubble clear,Grade 5,Reconstruction
366709001281,36,3603,360302,2,0,12,840,18,0,Flat,...,0,0,0,0,0,0,0,Damaged-Rubble clear,Grade 5,Reconstruction

### Compare Datasets

In [18]:
# Values of the original dataset
unique_values_district_id = original_data["district_id"].value_counts()
unique_values_vdcmun_id = original_data["vdcmun_id"].value_counts()
uniquq_values_ward_id = original_data["ward_id"].value_counts()
print(len(unique_values_district_id))
print(len(unique_values_vdcmun_id))
print(len(uniquq_values_ward_id))

11
110
945

In [19]:
# Values of the competition dataset
unique_values_geo_lvl_1_id = competition_data["geo_level_1_id"].value_counts()
unique_values_geo_lvl_2_id = competition_data["geo_level_2_id"].value_counts()
uniquq_values_geo_lvl_3_id = competition_data["geo_level_3_id"].value_counts()
print(len(unique_values_geo_lvl_1_id))
print(len(unique_values_geo_lvl_2_id))
print(len(uniquq_values_geo_lvl_3_id))

31
1414
11595